// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCShop.Infrastructure.Data;

#nullable disable

namespace PCShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109122326_RolesSeeded")]
    partial class RolesSeeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "389271c7-6194-48d3-8402-7b1b28430a42",
                            ConcurrencyStamp = "dfc1e3cb-1b61-45b1-84ae-43cba1d0225f",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "1b99a7a0-ca76-495f-9dff-2c486a558005",
                            ConcurrencyStamp = "23109158-0204-4bac-8af2-af50f5183e3a",
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DisplayCoverages");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DisplaySizes");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DisplayTechnologies");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshRates");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensitivities");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SSDCapacities");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoCards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("HasMicrophone")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Headphones");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("TypeId");

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CPUId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RAMId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<int>("SSDCapacityId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("VideoCardId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CPUId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplayCoverageId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("RAMId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("SSDCapacityId");

                    b.HasIndex("TypeId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Microphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Microphones");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RefreshRateId")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplayCoverageId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("RefreshRateId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("TypeId");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SensitivityId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SensitivityId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mice");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandHeadphones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorHeadphones")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeHeadphones")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandKeyboards")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorKeyboards")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", "Format")
                        .WithMany("FormatKeyboards")
                        .HasForeignKey("FormatId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeKeyboards")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Format");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandLaptops")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", "CPU")
                        .WithMany("CPULaptops")
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorLaptops")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", "DisplayCoverage")
                        .WithMany("DisplayCoverageLaptops")
                        .HasForeignKey("DisplayCoverageId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeLaptops")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyLaptops")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", "RAM")
                        .WithMany("RAMLaptops")
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", "Resolution")
                        .WithMany("ResolutionLaptops")
                        .HasForeignKey("ResolutionId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", "SSDCapacity")
                        .WithMany("SSDCapacityLaptops")
                        .HasForeignKey("SSDCapacityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeLaptops")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", "VideoCard")
                        .WithMany("VideoCardLaptops")
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CPU");

                    b.Navigation("Color");

                    b.Navigation("DisplayCoverage");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("RAM");

                    b.Navigation("Resolution");

                    b.Navigation("SSDCapacity");

                    b.Navigation("Type");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Microphone", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMicrophones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMicrophones")
                        .HasForeignKey("ColorId");

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Monitor", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMonitors")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMonitors")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", "DisplayCoverage")
                        .WithMany("DisplayCoverageMonitors")
                        .HasForeignKey("DisplayCoverageId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeMonitors")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyMonitors")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", "RefreshRate")
                        .WithMany("RefreshRateMonitors")
                        .HasForeignKey("RefreshRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", "Resolution")
                        .WithMany("ResolutionMonitors")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeMonitors")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("DisplayCoverage");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("RefreshRate");

                    b.Navigation("Resolution");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMice")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMice")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", "Sensitivity")
                        .WithMany("SensitivityMice")
                        .HasForeignKey("SensitivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeMice")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Sensitivity");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", b =>
                {
                    b.Navigation("BrandHeadphones");

                    b.Navigation("BrandKeyboards");

                    b.Navigation("BrandLaptops");

                    b.Navigation("BrandMice");

                    b.Navigation("BrandMicrophones");

                    b.Navigation("BrandMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", b =>
                {
                    b.Navigation("ColorHeadphones");

                    b.Navigation("ColorKeyboards");

                    b.Navigation("ColorLaptops");

                    b.Navigation("ColorMice");

                    b.Navigation("ColorMicrophones");

                    b.Navigation("ColorMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", b =>
                {
                    b.Navigation("CPULaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", b =>
                {
                    b.Navigation("DisplayCoverageLaptops");

                    b.Navigation("DisplayCoverageMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", b =>
                {
                    b.Navigation("DisplaySizeLaptops");

                    b.Navigation("DisplaySizeMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", b =>
                {
                    b.Navigation("DisplayTechnologyLaptops");

                    b.Navigation("DisplayTechnologyMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", b =>
                {
                    b.Navigation("FormatKeyboards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", b =>
                {
                    b.Navigation("RAMLaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", b =>
                {
                    b.Navigation("RefreshRateMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", b =>
                {
                    b.Navigation("ResolutionLaptops");

                    b.Navigation("ResolutionMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", b =>
                {
                    b.Navigation("SensitivityMice");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", b =>
                {
                    b.Navigation("SSDCapacityLaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", b =>
                {
                    b.Navigation("TypeHeadphones");

                    b.Navigation("TypeKeyboards");

                    b.Navigation("TypeLaptops");

                    b.Navigation("TypeMice");

                    b.Navigation("TypeMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", b =>
                {
                    b.Navigation("VideoCardLaptops");
                });
#pragma warning restore 612, 618
        }
    }
}
