// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCShop.Infrastructure.Data;

#nullable disable

namespace PCShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109132019_UsersSeeded")]
    partial class UsersSeeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "389271c7-6194-48d3-8402-7b1b28430a42",
                            ConcurrencyStamp = "256756ab-4e12-4072-8faa-b2b6d262b886",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "1b99a7a0-ca76-495f-9dff-2c486a558005",
                            ConcurrencyStamp = "b827eddf-2ac9-4169-b2c8-cc76cae95c1e",
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountOfPurchases")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "19512f55-7aa0-4707-b60d-6588f20c2ab1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9ed0bd7-0b0a-45b3-8f9b-c68c59299979",
                            CountOfPurchases = 0,
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin-FN",
                            LastName = "Admin-LN",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJcwHd8SHeAspsifxCQFOpnDuxK7NJgvOldxwZPane2LKQT8mIldzlZBEcL88AskbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1fe6daa5-2f5f-4e73-b683-e08cb78ae26a",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "fdf4e641-9248-44d4-8d23-ca09ad4ad793",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bde7aee2-41f6-47c4-9cf8-e030ba248c2b",
                            CountOfPurchases = 7,
                            Email = "superUser@mail.com",
                            EmailConfirmed = false,
                            FirstName = "SuperUser-FN",
                            LastName = "SuperUser-LN",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERUSER@MAIL.COM",
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEOexJhaqgGdL4pYzlOb7gDtHV2y5XslvjiUlLwVQOCXm9QBhDVvZ/qFSViTjyShWLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b105d3ce-ccc2-413d-8642-8abcdad66f05",
                            TwoFactorEnabled = false,
                            UserName = "superUser"
                        },
                        new
                        {
                            Id = "b3b38c01-9e6d-4faf-83d5-e0ec48d26115",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "016f4cfc-0add-4fdd-8ded-8d0d776eddd0",
                            CountOfPurchases = 0,
                            Email = "user@mail.com",
                            EmailConfirmed = false,
                            FirstName = "User-FN",
                            LastName = "User-LN",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAEAACcQAAAAEDmQxMcQbSOM5DZ3jdxz8GHwMP0qzCImWW4bw4IwOUWsegjt4ba7/SGMm4WDPg/q9g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28d2fada-6f9b-4a85-88c5-68b1e1889cb4",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DisplayCoverages");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DisplaySizes");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DisplayTechnologies");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshRates");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resolutions");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensitivities");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SSDCapacities");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoCards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("HasMicrophone")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Headphones");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Keyboards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CPUId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RAMId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<int>("SSDCapacityId")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("VideoCardId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CPUId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplayCoverageId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("RAMId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("SSDCapacityId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Microphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.ToTable("Microphones");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RefreshRateId")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplayCoverageId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("RefreshRateId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SensitivityId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SensitivityId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mice");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandHeadphones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorHeadphones")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Headphones")
                        .HasForeignKey("SellerId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeHeadphones")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandKeyboards")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorKeyboards")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", "Format")
                        .WithMany("FormatKeyboards")
                        .HasForeignKey("FormatId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Keyboards")
                        .HasForeignKey("SellerId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeKeyboards")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Format");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandLaptops")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", "CPU")
                        .WithMany("CPULaptops")
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorLaptops")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", "DisplayCoverage")
                        .WithMany("DisplayCoverageLaptops")
                        .HasForeignKey("DisplayCoverageId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeLaptops")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyLaptops")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", "RAM")
                        .WithMany("RAMLaptops")
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", "Resolution")
                        .WithMany("ResolutionLaptops")
                        .HasForeignKey("ResolutionId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", "SSDCapacity")
                        .WithMany("SSDCapacityLaptops")
                        .HasForeignKey("SSDCapacityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Laptops")
                        .HasForeignKey("SellerId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeLaptops")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", "VideoCard")
                        .WithMany("VideoCardLaptops")
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CPU");

                    b.Navigation("Color");

                    b.Navigation("DisplayCoverage");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("RAM");

                    b.Navigation("Resolution");

                    b.Navigation("SSDCapacity");

                    b.Navigation("Seller");

                    b.Navigation("Type");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Microphone", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMicrophones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMicrophones")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Microphones")
                        .HasForeignKey("SellerId");

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Monitor", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMonitors")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMonitors")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", "DisplayCoverage")
                        .WithMany("DisplayCoverageMonitors")
                        .HasForeignKey("DisplayCoverageId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeMonitors")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyMonitors")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", "RefreshRate")
                        .WithMany("RefreshRateMonitors")
                        .HasForeignKey("RefreshRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", "Resolution")
                        .WithMany("ResolutionMonitors")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Monitors")
                        .HasForeignKey("SellerId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeMonitors")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("DisplayCoverage");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("RefreshRate");

                    b.Navigation("Resolution");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", "Brand")
                        .WithMany("BrandMice")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", "Color")
                        .WithMany("ColorMice")
                        .HasForeignKey("ColorId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.Account.User", "Seller")
                        .WithMany("Mice")
                        .HasForeignKey("SellerId");

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", "Sensitivity")
                        .WithMany("SensitivityMice")
                        .HasForeignKey("SensitivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", "Type")
                        .WithMany("TypeMice")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");

                    b.Navigation("Sensitivity");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.Account.User", b =>
                {
                    b.Navigation("Headphones");

                    b.Navigation("Keyboards");

                    b.Navigation("Laptops");

                    b.Navigation("Mice");

                    b.Navigation("Microphones");

                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Brand", b =>
                {
                    b.Navigation("BrandHeadphones");

                    b.Navigation("BrandKeyboards");

                    b.Navigation("BrandLaptops");

                    b.Navigation("BrandMice");

                    b.Navigation("BrandMicrophones");

                    b.Navigation("BrandMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Color", b =>
                {
                    b.Navigation("ColorHeadphones");

                    b.Navigation("ColorKeyboards");

                    b.Navigation("ColorLaptops");

                    b.Navigation("ColorMice");

                    b.Navigation("ColorMicrophones");

                    b.Navigation("ColorMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.CPU", b =>
                {
                    b.Navigation("CPULaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayCoverage", b =>
                {
                    b.Navigation("DisplayCoverageLaptops");

                    b.Navigation("DisplayCoverageMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplaySize", b =>
                {
                    b.Navigation("DisplaySizeLaptops");

                    b.Navigation("DisplaySizeMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.DisplayTechnology", b =>
                {
                    b.Navigation("DisplayTechnologyLaptops");

                    b.Navigation("DisplayTechnologyMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Format", b =>
                {
                    b.Navigation("FormatKeyboards");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RAM", b =>
                {
                    b.Navigation("RAMLaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.RefreshRate", b =>
                {
                    b.Navigation("RefreshRateMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Resolution", b =>
                {
                    b.Navigation("ResolutionLaptops");

                    b.Navigation("ResolutionMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Sensitivity", b =>
                {
                    b.Navigation("SensitivityMice");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.SSDCapacity", b =>
                {
                    b.Navigation("SSDCapacityLaptops");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.Type", b =>
                {
                    b.Navigation("TypeHeadphones");

                    b.Navigation("TypeKeyboards");

                    b.Navigation("TypeLaptops");

                    b.Navigation("TypeMice");

                    b.Navigation("TypeMonitors");
                });

            modelBuilder.Entity("PCShop.Infrastructure.Data.Models.GravitatingClasses.VideoCard", b =>
                {
                    b.Navigation("VideoCardLaptops");
                });
#pragma warning restore 612, 618
        }
    }
}
